# Generated by Django 3.0.8 on 2020-07-11 06:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20, verbose_name='Word')),
                ('mean', models.CharField(max_length=200, verbose_name='Mean')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'word',
            },
        ),
    ]
